#!/usr/bin/env make
override blackbox/:=*

ifeq ($(origin .FEATURES),undefined)
  $(error `make` executable version `$(MAKE_VERSION)` is not supported. GNU Make 4.3 or above is required)
endif

ifeq ($(words $(MAKEFILE_LIST)),1)
  $(error `Makefile` should be included, direct usage is not allowed)
endif

ifeq ($(shell which docker),)
  $(error `docker` executable is required)
endif

override SHELL:=/usr/bin/env bash -e +o pipefail

ifeq ($(shell echo $$BASH),)
  $(error current shell executable is not supported. GNU Bash 5.1 or above is required)
endif

ifeq ($(origin .FEATURES),undefined)
  $(error `make` executable version "$(MAKE_VERSION)" is not supported. GNU Make 3.82 or above is required)
endif

override SHELL:=/bin/bash

ifneq ($(value SHELL),$(shell echo $$BASH))
  $(error current shell executable is not supported. GNU Bash 4.3 or above is required)
endif

override blackbox/host/tests/dir:=$(abspath $(dir $(lastword $(MAKEFILE_LIST))))
override blackbox/host/test/dir:=$(abspath $(dir $(firstword $(MAKEFILE_LIST))))
override blackbox/spawn/username:=ubuntu
override blackbox/spawn/test/dir:=/test

export BLACKBOX_HOST_TEST_DIR=$(blackbox/host/test/dir)
export BLACKBOX_FLAG__DEBUG_MODE=no
export VAGRANT_VAGRANTFILE=$(blackbox/host/tests/dir)/Vagrantfile

debug: ;@:
	$(eval BLACKBOX_FLAG__DEBUG_MODE:=yes)
	$(foreach variable,BLACKBOX_FLAG__DEBUG_MODE,$(info $(shell printf "\033[0;37m%s = %s\033[0m" "$(variable)" "$($(variable))")))
	$(info $(shell printf "\033[0;37m%s\033[0m" \\))
	$(foreach variable,$(filter-out BLACKBOX_FLAG__%,$(filter BLACKBOX_%,$(sort $(.VARIABLES)))),$(info $(shell printf "\033[0;37m%s = %s\033[0m" "$(variable)" "$($(variable))")))
	$(if $(and $(filter-out $(words $(MAKECMDGOALS)),0),$(filter-out $(words $(MAKECMDGOALS)),1)),$(info $(shell printf "\033[0;37m%s\033[0m" --)))

all: install setup save check
	$(MAKE) restore solve check

install:
	vagrant up

setup:
	vagrant ssh --command="sudo BLACKBOX_FLAG__DEBUG_MODE=$(BLACKBOX_FLAG__DEBUG_MODE) bash $(blackbox/spawn/test/dir)/setup.sh"

solve:
	vagrant ssh --command="sudo -i -u $(blackbox/spawn/username) bash $(blackbox/spawn/test/dir)/solve.sh"

check:
	vagrant ssh --command="sudo BLACKBOX_FLAG__DEBUG_MODE=$(BLACKBOX_FLAG__DEBUG_MODE) bash $(blackbox/spawn/test/dir)/check.sh" | tee >(awk '/Partial Credit/ { if (!reset) { reset = 1; next }; total_score += $$3; ok += ($$3 > 0); failed += ($$3 == 0) } END { printf("\nSuccess: %d\nFail: %d\nTotal: %d\n--\nTotal Credit: %d\n", ok, failed, ok + failed, total_score) }')

check\:evaluate:
	vagrant ssh --command="sudo BLACKBOX_FLAG__DEBUG_MODE=no BLACKBOX_FLAG__STEP_PROVISION=no BLACKBOX_FLAG__STEP_BUILD=no BLACKBOX_FLAG__STEP_EVALUATE=yes bash $(blackbox/spawn/test/dir)/check.sh" | tee >(awk '/Partial Credit/ { if (!reset) { reset = 1; next }; total_score += $$3; ok += ($$3 > 0); failed += ($$3 == 0) } END { printf("\nSuccess: %d\nFail: %d\nTotal: %d\n--\nTotal Credit: %d\n", ok, failed, ok + failed, total_score) }')

shell:
	vagrant ssh --command="sudo su - $(blackbox/spawn/username)"

shell\:spawn:
	vagrant ssh --command="sudo docker exec -it -w /home/ubuntu/test blackbox-spawn bash"

save:
	vagrant snapshot save current

restore:
	vagrant snapshot restore current

prune:
	vagrant snapshot delete current

uninstall:
	vagrant destroy -f
	rm -rf .vagrant
