#!/usr/bin/env bash
# @file module/redis-stdl/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/redis-stdl/check.action
# @description Redis standalone module "check" action

# @section blackbox.module.redis-stdl.*
blackbox.module.redis-stdl.check() {
  # shellcheck disable=SC2034
  typeset question_id=$1
  typeset -a step_args=("${@:2}")

  {
    blackbox.framework.trace "${FUNCNAME[0]}" "$*" <<<""
  }

  if [ ! -e "/blackbox/module/${BLACKBOX_MODULE_NAME}/check.action" ]; then
    blackbox.framework.exception.raise "action '%s:check' not found" "$BLACKBOX_MODULE_NAME"
  fi

  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.check.provision:step" "${step_args[@]}"
  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.check.evaluate:step" "${step_args[@]}"

  : <<< blackbox.module.*.check
}
