#!/usr/bin/env bash
# @file module/kubernetes/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/master/module/kubernetes/check.action
# @description Kubernetes module "check" action

# @section blackbox.module.kubernetes.*
blackbox.module.kubernetes.check() {
  : <<< blackbox.framework.module.abstract.check:action
}
