---
- hosts: localhost
  strategy: "{{ 'debug' if (lookup('env', 'BLACKBOX_FLAG__DEBUG_MODE') == 'yes') else 'linear' }}"
  gather_facts: false
  tasks:
    - shell: printenv
      register: printenv
    - debug:
        msg: "{{ printenv.stdout_lines | sort }}"
      when: lookup("env", "BLACKBOX_FLAG__DEBUG_MODE") == "yes"
    - shell: |
        docker ps -aq | xargs -r docker stop
        docker system prune -af --volumes
      when: lookup("env", "BLACKBOX_FLAG__STEP_BUILD") == "yes"
    - docker_container:
        image: ubuntu:bionic
        name: "{{ lookup('env', 'BLACKBOX_SPAWN') }}"
        hostname: "{{ lookup('env', 'BLACKBOX_SPAWN') }}"
        detach: true
        interactive: true
        privileged: true
        volumes:
          - /blackbox:/blackbox:ro
          - "/home/{{ lookup('env', 'BLACKBOX_USER_NAME') }}:/home/{{ lookup('env', 'BLACKBOX_USER_NAME') }}"
    - add_host:
        name: "{{ lookup('env','BLACKBOX_SPAWN') }}"
        ansible_connection: docker
- hosts: "{{ lookup('env', 'BLACKBOX_SPAWN') if (lookup('env', 'BLACKBOX_FLAG__STEP_BUILD') == 'yes') else 'dead' }}"
  gather_facts: false
  tasks:
    - raw: ln -s /blackbox/blackbox /dev/blackbox
    - raw: "groupadd -g {{ lookup('env', 'BLACKBOX_USER').split(':')[1] }} {{ lookup('env', 'BLACKBOX_USER_NAME') }}"
    - raw: "useradd -u {{ lookup('env', 'BLACKBOX_USER').split(':')[0] }} -g {{ lookup('env', 'BLACKBOX_USER').split(':')[1] }}  -s /bin/bash -M {{ lookup('env', 'BLACKBOX_USER_NAME') }}"
    - raw: apt-get update
    - raw: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends software-properties-common python
    - raw: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo wget
    - raw: echo 'shopt -os allexport; . /etc/environment; shopt -ou allexport' >>/root/.bashrc
    - apt:
        pkg:
          - sudo
          - wget
        state: latest
        update_cache: no
        install_recommends: no
- hosts: "{{ lookup('env', 'BLACKBOX_SPAWN') if (lookup('env', 'BLACKBOX_BUILD_WITH_OPTS') != '') else 'dead' }}"
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ lookup('env', 'BLACKBOX_BUILD_WITH_OPTS') }}"
    - shell: |
        source /dev/blackbox >/dev/null;
        {{ lookup('env', 'BLACKBOX_BUILD_WITH_OPTS') }}
      args:
        executable: /bin/bash
        chdir: "{{ lookup('env', 'BLACKBOX_USER_QUESTION_DIRECTORY') }}"
