#!/usr/bin/env bash
# @file module/ansible/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/ansible/check.action
# @description Ansible module "check" action

# @section blackbox.module.ansible.*
blackbox.module.ansible.check() {
  : <<< blackbox.framework.module.abstract.check:action
}
