#!/usr/bin/env bash
blackbox.module.ansible.score() {
  typeset question_id=$1
  typeset -a step_args=("${@:2}")

  blackbox.trace.entrypoint score.action "${FUNCNAME[0]}" "$*"

  if (( ! ${#step_args[@]} )); then
    step_args=("")
  fi

  blackbox.module.load ansible/score/provision.step "${step_args[@]}"
  blackbox.module.load ansible/score/build.step "${step_args[@]}"

  blackbox.module.load ansible/score/evaluate.step "${step_args[@]}" && {
    local -a override_from=(
      blackbox.module.ansible.score.evaluate.expect.artifact.collection
      blackbox.module.ansible.score.evaluate.expect.file.exists
      blackbox.module.ansible.score.evaluate.expect.shell.debug
      blackbox.module.ansible.score.evaluate.expect.shell.failure
      blackbox.module.ansible.score.evaluate.expect.shell.stderr
      blackbox.module.ansible.score.evaluate.expect.shell.stdout
      blackbox.module.ansible.score.evaluate.expect.shell.success
    )

    for override_definition in "${override_from[@]}"; do
      local override_to=${override_definition/module.ansible.score.evaluate./}

      if ( ! blackbox.flag.enabled STEP_EVALUATE ); then
        override_definition=
      fi

      blackbox.module.override "$override_to" "$override_definition"
    done
  }
}; blackbox.module.ansible.score "$@"
