#!/usr/bin/env bash
# @file module/ansible/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/ansible/setup.action
# @description Ansible module "setup" action

# @section blackbox.module.ansible.*
blackbox.module.ansible.setup() {
  : <<< blackbox.framework.module.abstract.setup:action
}
