#!/usr/bin/env bash

blackbox.module.ansible.setup() {
  if ( blackbox.flag.enabled MODULES_DO_PROVISION ); then
      blackbox.inventory.provision docker && {
        usermod -aG docker "$BLACKBOX_HOST_USERNAME"
        blackbox.inventory.service docker start
      }

      blackbox.inventory.provision ansible python-docker && {
        blackbox.transport.fetch module/ansible/setup/rootfs/etc/blackbox/ansible/playbook.yml | install -m 0644 -D /dev/stdin /etc/blackbox/ansible/playbook.yml

        if [ ! -e "/home/${BLACKBOX_HOST_USERNAME}/solution/playbook.yml" ]; then
          install -o "$BLACKBOX_HOST_USERNAME" -g "$(getent group "$BLACKBOX_HOST_USERNAME" | cut -d ":" -f 1)" -m 0775 -d "/home/${BLACKBOX_HOST_USERNAME}/solution" && {
            blackbox.transport.fetch module/ansible/setup/rootfs/home/%/solution/playbook.yml | install -o "$BLACKBOX_HOST_USERNAME" -g "$(getent group "$BLACKBOX_HOST_USERNAME" | cut -d ":" -f 1)" -m 0664 /dev/stdin "/home/${BLACKBOX_HOST_USERNAME}/solution/playbook.yml"
          }
        fi
      }
  fi

  if ( blackbox.flag.enabled MODULES_DO_CONFIGURE ); then
    blackbox.configurator.load && {
      blackbox.configurator.configure
    }
  fi
}; blackbox.module.ansible.setup
