#!/usr/bin/env bash
# @file module/linux-stdl/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/linux-stdl/setup.action
# @description Linux standalone module "setup" action

# @section blackbox.module.linux-stdl.*
blackbox.module.linux-stdl.setup() {
  # shellcheck disable=SC2034
  typeset question_id=$1
  typeset -a step_args=("${@:2}")

  {
    blackbox.framework.trace "${FUNCNAME[0]}" "$*" <<<""
  }

  if [ ! -e "/blackbox/module/${BLACKBOX_MODULE_NAME}/setup.action" ]; then
    blackbox.framework.exception.raise "action '%s:setup' not found" "$BLACKBOX_MODULE_NAME"
  fi

  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.setup.provision:step" "${step_args[@]}"

  : <<< blackbox.module.*.setup
}
