#!/usr/bin/env bash
# @file module/ansible-aws/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/ansible-aws/check.action
# @description Ansible+AWS "check" action

# @section blackbox.module.ansible-aws.*
blackbox.module.ansible-aws.check() {
  : <<< blackbox.framework.module.abstract.check:action
}
