#!/usr/bin/env bash
# @file module/ansible-aws/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/master/module/ansible-aws/setup.action
# @description Ansible+AWS "setup" action

# @section blackbox.module.ansible-aws.*
blackbox.module.ansible-aws.setup() {
  : <<< blackbox.framework.module.abstract.setup:action
}
