#!/usr/bin/env bash
# @file framework/module/abstract/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/framework/module/abstract/check.action
# @description Abstract module "check" action

# @section blackbox.framework.module.abstract.*

# Implements a common logical part of "check" action that each module inherits
#
# @arg $1 type=string Question ID
# @arg $2 type=...mixed Step args
#
# @example
#   #!/usr/bin/env bash
#   # Example of a module "check" action inheriting an abstraction
#   blackbox.module.my-module.check() {
#     # do something (if needed), then specify where the abstraction should be applied
#     : <<< blackbox.framework.module.abstract.check:action
#     # do something (if needed)
#   }
blackbox.framework.module.abstract.check() {
  # shellcheck disable=SC2034
  typeset question_id=$1
  typeset -a step_args=("${@:2}")

  {
    blackbox.framework.trace "${FUNCNAME[0]}" "$*" <<<""
  }

  if [ ! -e "/blackbox/module/${BLACKBOX_MODULE_NAME}/check.action" ]; then
    blackbox.framework.exception.raise "action '%s:check' not found" "$BLACKBOX_MODULE_NAME"
  fi

  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.check.provision:step" "${step_args[@]}"
  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.check.build:step" "${step_args[@]}"
  blackbox.framework.import "blackbox.module.${BLACKBOX_MODULE_NAME}.check.evaluate:step" "${step_args[@]}"

  : <<< blackbox.module.*.check
}
