#!/usr/bin/env bash
# @file module/puppet/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/puppet/setup.action
# @description Puppet module "setup" action

# @section blackbox.module.puppet.*
blackbox.module.puppet.setup() {
  : <<< blackbox.framework.module.abstract.setup:action
}
