#!/usr/bin/env bash
# @file module/shell/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/shell/check.action
# @description Shell module "check" action

# @section blackbox.module.shell.*
blackbox.module.shell.check() {
  : <<< blackbox.framework.module.abstract.check:action
}
