client
dev tun
proto udp
remote [SERVER_ADDRESS] 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca [CA_CRT_PATH]
cert [CLIENT_CRT_PATH]
key [CLIENT_KEY_PATH]
remote-cert-tls server
cipher AES-256-CBC
verb 3
