client
dev tun
proto udp
remote server.address 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca /path/to/ca.crt
cert /path/to/client.crt
key /path/to/client.key
remote-cert-tls server
cipher AES-256-CBC
verb 3
