#!/usr/bin/env make
include ../../../../framework/module/abstract/score/provision/Makefile

override blackbox/module/docker/score/provision/:=*

BLACKBOX_USER:=1000:1000
BLACKBOX_USER_NAME:=ubuntu
BLACKBOX_USER_HOME:=/home/$(BLACKBOX_USER_NAME)
BLACKBOX_VERSION:=master
