#!/usr/bin/env bash
# @file module/terraform-aws/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/terraform-aws/setup.action
# @description Terraform+AWS module "setup" action

# @section blackbox.module.terraform-aws.*
blackbox.module.terraform-aws.setup() {
  : <<< blackbox.framework.module.abstract.setup:action
}
