#!/usr/bin/env bash
# @file module/aws/setup.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/aws/setup.action
# @description AWS module "setup" action

# @section blackbox.module.aws.*
blackbox.module.aws.setup() {
  : <<< blackbox.framework.module.abstract.setup:action
}
