name: Blackbox build
on:
  push:
    branches:
      - "2204"
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
      - name: Login to Amazon ECR public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Login to Amazon ECR private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "134148934511"
      - name: Build Blackbox
        run: |
          make \
            --file=Makefile.workflow \
            github:build:blackbox
      - name: Build Blackbox modules
        run: |
          make \
            --file=Makefile.workflow \
            github:build:blackbox:modules
      - name: Push Blackbox
        run: |
          make \
            --file=Makefile.workflow \
            github:push:blackbox
      - name: Push Blackbox modules
        run: |
          make \
            --file=Makefile.workflow \
            github:push:blackbox:modules
