name: Amazon ECR private registry charge
on:
  push:
    branches:
      - "2204"
    paths:
      - ".github/workflows/ecr.yml"
      - ".github/workflows/ecr/**"
      - "Makefile.workflow"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
      - name: Login to Amazon ECR public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Login to Amazon ECR private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "134148934511"
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/801133-ansible
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/801133-ansible
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              problemsetters/801133-ansible:latest@sha256:83eefb4ed2c7a0dfabe489d23aa3be19b389f3e73524f6cb1c2746cc8bae9658 \
              hr/801133-ansible:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/busybox
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/busybox
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/busybox:latest@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f \
              hr/busybox:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/gcc
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/gcc
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/gcc:latest@sha256:4e934397c1eaac263babffa0da20138052ec6098dd90830850eb168f38d55e87 \
              hr/gcc:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/httpd
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/httpd
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/httpd:latest@sha256:391a8eb0c1ed464163da46099606a5ec293705118f3054d6c60f5957e2485bd0 \
              hr/httpd:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/http-echo
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/http-echo
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              hashicorp/http-echo:latest@sha256:fcb75f691c8b0414d670ae570240cbf95502cc18a9ba57e982ecac589760a186 \
              hr/http-echo:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/localstack
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/localstack
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/localstack/localstack:2.1.0@sha256:74c3cb7cfa3d8a8ea9e786c0974dddf6ea60e7cea91e7a739f93cecafc09a9e2 \
              hr/localstack:2.1.0
          make \
            --file=Makefile.workflow \
            github:ecr:repository:build \
              hr/localstack/2.1.0-slim \
              hr/localstack:2.1.0-slim
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              hr/localstack:2.1.0-slim \
              hr/localstack:2.1.0-slim
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/mariadb
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/mariadb
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/mariadb:latest@sha256:81e893032978c4bf8ad43710b7a979774ed90787fa32d199162148ce28fe3b76 \
              hr/mariadb:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/mongo
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/mongo
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/mongo:latest@sha256:1cb283500219e8fc0b61b328ea5a199a395a753d88b17351c58874fb425223cb \
              hr/mongo:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/mysql
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/mysql
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb \
              hr/mysql:5.7
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/mysql:latest@sha256:0596fa224cdf3b3355ce3ddbfd7ce77be27ec9e51841dfc5d2e1c8b81eea69d2 \
              hr/mysql:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/nginx
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/nginx
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/nginx:1.20@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d \
              hr/nginx:1.20
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/nginx:1.27@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19 \
              hr/nginx:1.27
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/nginx:alpine@sha256:4ff102c5d78d254a6f0da062b3cf39eaf07f01eec0927fd21e219d0af8bc0591 \
              hr/nginx:alpine
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/nginx:latest@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19 \
              hr/nginx:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/node
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/node
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/node:12@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e \
              hr/node:12
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/php
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/php
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/php:8-cli@sha256:f9410ffdc12c9ab0b6c390a56e46a13ef58558f7c2abda1bc1bb3291a7d57452 \
              hr/php:8-cli
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/php:8.1-fpm@sha256:9711445cf92fbdeb42c4396ce4ad405ead54f38ff876d1093ec0abad98c75a16 \
              hr/php:8.1-fpm
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/php:fpm@sha256:182b3466ea500120199794457bc7563dfc599f742f6833722dc7d3ca3f69a328 \
              hr/php:fpm
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/python
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/python
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/python:3.9@sha256:bc2e05bca883473050fc3b7c134c28ab822be73126ba1ce29517d9e8b7f3703b \
              hr/python:3.9
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/python:3.9-slim@sha256:e52ca5f579cc58fed41efcbb55a0ed5dccf6c7a156cba76acfb4ab42fc19dd00 \
              hr/python:3.9-slim
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/redis
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/redis
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/redis:latest@sha256:bd41d55aae1ecff61b2fafd0d66761223fe94a60373eb6bb781cfbb570a84079 \
              hr/redis:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/ubuntu
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/ubuntu
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/ubuntu:22.04@sha256:ed1544e454989078f5dec1bfdabd8c5cc9c48e0705d07b678ab6ae3fb61952d2 \
              hr/ubuntu:22.04
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/ubuntu:focal-20230624@sha256:c9820a44b950956a790c354700c1166a7ec648bc0d215fa438d3a339812f1d01 \
              hr/ubuntu:focal-20230624
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              public.ecr.aws/docker/library/ubuntu:latest@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782 \
              hr/ubuntu:latest
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/ubuntu-sshd
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/ubuntu-sshd
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              rastasheep/ubuntu-sshd:18.04@sha256:1df808ccf95c13b8e62548ad434829bc28ee701a65624e5c0440fc24482e4a62 \
              hr/ubuntu-sshd:18.04 # TODO: retire this image in favor of "134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/ubuntu-sshd:22.04" or later
          make \
            --file=Makefile.workflow \
            github:ecr:repository:build \
              hr/ubuntu-sshd/22.04 \
              hr/ubuntu-sshd:22.04
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              hr/ubuntu-sshd:22.04 \
              hr/ubuntu-sshd:22.04
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/ubuntu-sshd-openvpn
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/ubuntu-sshd-openvpn
          make \
            --file=Makefile.workflow \
            github:ecr:repository:build \
              hr/ubuntu-sshd-openvpn/22.04 \
              hr/ubuntu-sshd-openvpn:22.04
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              hr/ubuntu-sshd-openvpn:22.04 \
              hr/ubuntu-sshd-openvpn:22.04
      - name: 134148934511.dkr.ecr.us-east-1.amazonaws.com/hr/ubuntu-sshd-wireguard
        run: |
          make \
            --file=Makefile.workflow \
            github:ecr:repository:initialize \
              hr/ubuntu-sshd-wireguard
          make \
            --file=Makefile.workflow \
            github:ecr:repository:build \
              hr/ubuntu-sshd-wireguard/22.04 \
              hr/ubuntu-sshd-wireguard:22.04
          make \
            --file=Makefile.workflow \
            github:ecr:repository:charge \
              hr/ubuntu-sshd-wireguard:22.04 \
              hr/ubuntu-sshd-wireguard:22.04
