#!/usr/bin/env bash
# @file module/docker/check.action
# @brief https://github.com/ProblemSetters/devops-blackbox/blob/2204/module/docker/check.action
# @description Docker module "check" action

# @section blackbox.module.docker.*
blackbox.module.docker.check() {
  : <<< blackbox.framework.module.abstract.check:action
}
