#!/usr/bin/env bash
blackbox.module.docker.setup() {
  typeset question_id=$1
  typeset -a step_args=("${@:2}")

  blackbox.trace.entrypoint setup.action "${FUNCNAME[0]}" "$*"

  if (( ! ${#step_args[@]} )); then
    step_args=("")
  fi

  blackbox.module.load docker/setup/provision.step "${step_args[@]}"
}; blackbox.module.docker.setup "$@"
